import type { Show, PastSet, Release } from "@/types";

const siteConfig = {
  artist: {
    name: "Benjamin Franklin",
    email: "booking@benjaminfranklinmusic.com",
  },

  assets: {
    logo: "/logo.png",
    logoTransparent: "/logo.png",
    avatar: "/avatar.jpg",
    heroImage: "/hero.jpg",
  },

  theme: {
    accent: "#c9a84c",
    background: "#0a0a0a",
    foreground: "#ededed",
    card: "#111113",
    border: "#1e1e22",
    primary: "#ffffff",
  },

  socials: {
    spotify: "https://open.spotify.com/artist/7GALLXYUZiyfa1gYGMJOHU",
    instagram: "https://instagram.com/benjaminfranklinmusic",
    soundcloud: "https://soundcloud.com/benjaminfranklin",
    tiktok: "https://tiktok.com/@benjamin.franklin2153",
  },

  navigation: [
    {
      key: "music",
      href: "/music",
      icon: "Music" as const,
    },
    {
      key: "shows",
      href: "/shows",
      icon: "Calendar" as const,
    },
    {
      key: "fanZone",
      href: "/fan-zone",
      icon: "Users" as const,
    },
  ],

  shows: {
    upcoming: [
      {
        id: "show-1",
        name: "Who The Fuck is Benjamin Franklin?",
        venue: "La Machine du Moulin Rouge",
        city: "Paris",
        country: "France",
        date: "2026-04-15T22:00:00",
        ticketUrl: "https://example.com/tickets/1",
      },
      {
        id: "show-2",
        name: "Latin House Night",
        venue: "Pacha",
        city: "Barcelona",
        country: "Spain",
        date: "2026-05-20T23:00:00",
      },
      {
        id: "show-3",
        name: "Summer Percussions",
        venue: "Ushuaia",
        city: "Ibiza",
        country: "Spain",
        date: "2026-06-10T16:00:00",
        ticketUrl: "https://example.com/tickets/3",
        soldOut: true,
      },
    ] as Show[],

    past: [
      {
        id: "past-1",
        name: "NYE Special - MIYU Records Showcase",
        venue: "Rex Club",
        city: "Paris",
        country: "France",
        date: "2025-12-31T23:00:00",
        tracklist: [
          "Benjamin Franklin - This Is MY House",
          "Benjamin Franklin & Lalita K - Peace In The World",
          "Benjamin Franklin - Ain't No Love",
          "Benjamin Franklin - Saudade",
          "Benjamin Franklin & Fabien Koufach feat Ortal - L'Amour Toujours",
          "Benjamin Franklin - THIS SOUND",
        ],
      },
      {
        id: "past-2",
        name: "Who The Fuck is Benjamin Franklin?",
        venue: "Wanderlust",
        city: "Paris",
        country: "France",
        date: "2025-10-15T22:00:00",
        tracklist: [
          "Benjamin Franklin - Chupa Sin Mano",
          "Benjamin Franklin - Try To Fight",
          "Sasha Kaay & Benjamin Franklin - Como Como",
          "Benjamin Franklin - God Save The World",
          "Benjamin Franklin - Pray For Tomorrow",
        ],
      },
      {
        id: "past-3",
        name: "Ultra Music Conference",
        venue: "WMC",
        city: "Miami",
        country: "USA",
        date: "2025-03-22T18:00:00",
      },
    ] as PastSet[],
  },

  releases: [
    {
      id: "release-1",
      title: "THIS SOUND",
      type: "single",
      releaseDate: "2025-06-16",
      coverUrl: "/covers/this-sound.jpg",
      audioUrl: "/audio/the-bomb-remix.mp3",
      featured: true,
    },
    {
      id: "release-2",
      title: "Ain't No Love",
      type: "single",
      releaseDate: "2025-05-15",
      coverUrl: "/covers/aint-no-love.jpg",
      audioUrl: "/audio/aint-no-love.mp3",
    },
    {
      id: "release-3",
      title: "Try To Fight",
      type: "single",
      releaseDate: "2025-06-02",
      coverUrl: "/covers/try-to-fight.jpg",
      audioUrl: "/audio/try-to-fight.mp3",
    },
    {
      id: "release-4",
      title: "Chupa Sin Mano",
      type: "single",
      releaseDate: "2025-10-29",
      coverUrl: "/covers/chupa-sin-mano.jpg",
      audioUrl: "/audio/chupa-sin-mano.mp3",
    },
    {
      id: "release-5",
      title: "This Is MY House",
      type: "single",
      releaseDate: "2024-09-03",
      coverUrl: "/covers/this-is-my-house.jpg",
      audioUrl: "/audio/this-is-my-house.mp3",
    },
    {
      id: "release-6",
      title: "Saudade",
      type: "single",
      releaseDate: "2025-02-19",
      coverUrl: "/covers/saudade.jpg",
      audioUrl: "/audio/saudade.mp3",
    },
    {
      id: "release-7",
      title: "Peace In The World",
      type: "single",
      releaseDate: "2024-06-11",
      coverUrl: "/covers/peace-in-the-world.jpg",
      audioUrl: "/audio/peace-in-the-world.mp3",
    },
    {
      id: "release-9",
      title: "God Save The World",
      type: "single",
      releaseDate: "2023-05-22",
      coverUrl: "/covers/god-save-the-world.jpg",
      audioUrl: "/audio/god-save-the-world.mp3",
    },
    {
      id: "release-10",
      title: "Como Como",
      type: "single",
      releaseDate: "2025-01-02",
      coverUrl: "/covers/como-como.jpg",
      audioUrl: "/audio/como-como.mp3",
    },
    {
      id: "release-11",
      title: "Pray For Tomorrow",
      type: "single",
      releaseDate: "2024-12-15",
      coverUrl: "/covers/pray-for-tomorrow.jpg",
      audioUrl: "/audio/pray-for-tomorrow.mp3",
    },
    {
      id: "release-12",
      title: "Respect For The DJ's (Underground Mix)",
      type: "remix",
      releaseDate: "2024-11-21",
      coverUrl: "/covers/respect-for-the-djs.jpg",
      audioUrl: "/audio/respect-for-the-djs.mp3",
    },
    {
      id: "release-13",
      title: "Mona Ki Ngi Xica",
      type: "single",
      releaseDate: "2024-08-23",
      coverUrl: "/covers/mona-ki-ngi-xica.jpg",
      audioUrl: "/audio/mona-ki-ngi-xica.mp3",
    },
    {
      id: "release-14",
      title: "Beautiful People (Remix)",
      type: "remix",
      releaseDate: "2024-10-04",
      coverUrl: "/covers/beautiful-people.jpg",
      audioUrl: "/audio/beautiful-people-remix.wav",
    },
    {
      id: "release-15",
      title: "The Way (Benjamin Franklin Remix)",
      type: "remix",
      releaseDate: "2024-08-27",
      coverUrl: "/covers/the-way-remix.jpg",
      audioUrl: "/audio/the-way-remix.mp3",
    },
    {
      id: "release-16",
      title: "What Goes Around",
      type: "single",
      releaseDate: "2025-03-22",
      coverUrl: "/covers/what-goes-around.jpg",
      audioUrl: "/audio/what-goes-around.mp3",
    },
    {
      id: "release-17",
      title: "Give It Up",
      type: "single",
      releaseDate: "2025-02-19",
      coverUrl: "/covers/give-it-up.jpg",
      audioUrl: "/audio/give-it-up.mp3",
    },
    {
      id: "release-18",
      title: "Sunset With You (Benjamin Franklin Remix)",
      type: "remix",
      releaseDate: "2025-04-17",
      coverUrl: "/covers/sunset-with-you-remix.jpg",
      audioUrl: "/audio/sunset-with-you-remix.mp3",
    },
    {
      id: "release-19",
      title: "Peace In The World (Buyabass Remix)",
      type: "remix",
      releaseDate: "2025-03-19",
      coverUrl: "/covers/peace-in-the-world-remix.jpg",
      audioUrl: "/audio/peace-in-the-world-remix.mp3",
    },
    {
      id: "release-20",
      title: "Only Me & You",
      type: "single",
      releaseDate: "2025-07-10",
      coverUrl: "/covers/only-me-and-you.jpg",
      audioUrl: "/audio/only-me-and-you.mp3",
    },
    {
      id: "release-21",
      title: "FAYA (Marbella Club Mix)",
      type: "single",
      releaseDate: "2025-08-01",
      coverUrl: "/covers/faya.jpg",
      audioUrl: "/audio/faya.mp3",
    },
    {
      id: "release-22",
      title: "Running",
      type: "single",
      releaseDate: "2025-09-15",
      coverUrl: "/covers/running.jpg",
      audioUrl: "/audio/running.mp3",
    },
    {
      id: "release-23",
      title: "Na Na Na Na",
      type: "single",
      releaseDate: "2025-10-01",
      coverUrl: "/covers/na-na-na-na.jpeg",
      audioUrl: "/audio/na-na-na-na.wav",
    },
    {
      id: "release-24",
      title: "Hakuna",
      type: "single",
      releaseDate: "2025-11-01",
      coverUrl: "/covers/hakuna.jpg",
      audioUrl: "/audio/hakuna.mp3",
    },
    {
      id: "release-25",
      title: "Build At Home (Remix)",
      type: "remix",
      releaseDate: "2025-11-15",
      coverUrl: "/covers/build-at-home-remix.jpg",
      audioUrl: "/audio/build-at-home-remix.mp3",
    },
    {
      id: "release-26",
      title: "Mattina",
      type: "single",
      releaseDate: "2025-12-01",
      coverUrl: "/covers/mattina.jpg",
      audioUrl: "/audio/mattina.mp3",
    },
    {
      id: "release-27",
      title: "Para Bailar",
      type: "single",
      releaseDate: "2025-12-15",
      coverUrl: "/covers/para-bailar.png",
      audioUrl: "/audio/para-bailar.mp3",
    },
  ] as Release[],

  fanZone: {
    djPassword: "wtfisbf2026",
  },

  live: {
    adminPassword: "wtfisbf2026",
  },

  booking: {
    recipientEmail: "booking@benjaminfranklinmusic.com",
    eventTypeKeys: ["club", "festival", "private", "corporate", "wedding", "other"] as const,
    budgetRangeKeys: ["under1k", "1kTo3k", "3kTo5k", "5kTo10k", "over10k"] as const,
  },
};

export default siteConfig;
